# Generated by Django 4.2.16 on 2024-10-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benutzer', '0003_alter_benutzer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benutzer',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to='profile_avatars'),
        ),
        migrations.AddField(
            model_name='historicalbenutzer',
            name='avatar',
            field=models.TextField(default='avatar.jpg', max_length=100),
        ),
    ]
