# Generated by Django 4.2.16 on 2024-10-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WanderStrecke',
            fields=[
                ('id', models.AutoField(db_column='wst_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(db_column='wst_txt', default='<unbenannt>', max_length=512, verbose_name='Bezeichnung')),
                ('json', models.FileField(upload_to='', verbose_name='JSON-Datei')),
            ],
            options={
                'verbose_name': 'WanderStrecke',
                'verbose_name_plural': 'WanderStrecken',
                'db_table': 'wanderstrecke',
                'ordering': ['bezeichnung'],
            },
        ),
    ]
