# Generated by Django 4.2.16 on 2024-10-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderstrecke', '0002_wanderstrecke_benutzer'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanderstrecke',
            name='beschreibung',
            field=models.CharField(db_column='wst_bsc', default='<ohne Beschreibung>', max_length=8192, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='wanderstrecke',
            name='bild',
            field=models.FileField(default='wanderstrecke.jpg', upload_to='bilder_wanderstrecke', verbose_name='Bilddatei'),
        ),
    ]
