# Generated by Django 4.2.16 on 2024-10-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderstrecke', '0005_alter_wanderstrecke_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WanderPunkt',
            fields=[
                ('id', models.AutoField(db_column='wst_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(db_column='wpt_txt', default='<unbenannt>', max_length=512, verbose_name='Bezeichnung')),
                ('beschreibung', models.CharField(db_column='wpt_bsc', default='<ohne Beschreibung>', max_length=8192, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Wanderpunkt',
                'verbose_name_plural': 'Wanderpunkte',
                'db_table': 'wanderpunkt',
                'ordering': ['bezeichnung'],
            },
        ),
    ]
