# Generated by Django 4.2.16 on 2024-10-26 15:13

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('wanderstrecke', '0006_wanderpunkt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanderstrecke',
            name='bild',
            field=django_resized.forms.ResizedImageField(crop=None, default='wanderstrecke.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='bilder_wanderstrecke', verbose_name='Bilddatei'),
        ),
    ]
