# Generated by Django 4.2.16 on 2024-10-28 16:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanderstrecke', '0008_alter_wanderstrecke_bild'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanderpunkt',
            name='ort',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Ort'),
        ),
    ]
