# Generated by Django 4.2.16 on 2024-10-29 14:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wanderstrecke', '0009_wanderpunkt_ort'),
    ]

    operations = [
        migrations.CreateModel(
            name='WanderAbschnitt',
            fields=[
                ('id', models.AutoField(db_column='wst_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(db_column='wpt_txt', default='<unbenannt>', max_length=512, verbose_name='Bezeichnung')),
                ('beschreibung', models.CharField(db_column='wpt_bsc', default='<ohne Beschreibung>', max_length=8192, verbose_name='Beschreibung')),
                ('strecke', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='Streckenführung')),
                ('ort1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wanderabschnitt_set1', to='wanderstrecke.wanderpunkt')),
                ('ort2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wanderabschnitt_set2', to='wanderstrecke.wanderpunkt')),
            ],
            options={
                'verbose_name': 'Wanderabschnitt',
                'verbose_name_plural': 'Wanderabschnitte',
                'db_table': 'wanderabschnitt',
                'ordering': ['bezeichnung'],
            },
        ),
    ]
