# Generated by Django 4.2.16 on 2024-10-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderstrecke', '0010_wanderabschnitt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wanderstrecke',
            name='json',
        ),
        migrations.RemoveField(
            model_name='wanderstrecke',
            name='url',
        ),
        migrations.AddField(
            model_name='wanderabschnitt',
            name='json',
            field=models.FileField(null=True, upload_to='', verbose_name='JSON-Datei'),
        ),
        migrations.AddField(
            model_name='wanderabschnitt',
            name='url',
            field=models.CharField(db_column='wst_url', default='<leer>', max_length=65536, verbose_name='Link zum Teilen auf strecken-messen.de'),
        ),
    ]
