# Generated by Django 4.2.16 on 2024-10-30 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wanderstrecke', '0011_remove_wanderstrecke_json_remove_wanderstrecke_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanderabschnitt',
            name='wanderstrecke',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wanderstrecke.wanderstrecke'),
        ),
    ]
