# Generated by Django 4.2.16 on 2024-10-31 07:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanderstrecke', '0012_wanderabschnitt_wanderstrecke'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanderabschnitt',
            name='startzpunkt',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Startpunkt'),
        ),
    ]
