# Generated by Django 4.2.16 on 2024-10-31 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanderstrecke', '0013_wanderabschnitt_startzpunkt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wanderabschnitt',
            old_name='startzpunkt',
            new_name='startpunkt',
        ),
    ]
